name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Pull image from Docker Hub
      run: sudo docker pull doitformellc/harborgroupusa:latest

    - name: Delete old container
      run: sudo docker rm -f harborgroupusa-container || true  # Fixed typo here

    - name: Run Docker Container
      run: |
        sudo docker run -d -p 3000:3000 --name harborgroupusa-container \
           -e ACCESSKEY="${{ secrets.ACCESSKEY }}" \
           -e BUCKET="${{ secrets.BUCKET }}" \
           -e DATABASE="${{ secrets.DATABASE }}" \
           -e USER="${{ secrets.USER }}" \
           -e PASSWORD="${{ secrets.PASSWORD }}" \
           -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
           -e REGION="${{ secrets.REGION }}" \
           -e SECRETKEY="${{ secrets.SECRETKEY }}" \
           -e HOST="${{ secrets.HOST }}" \
           -e EMAIL_HOST="${{ secrets.EMAIL_HOST }}" \
           -e EMAIL_PORT="${{ secrets.EMAIL_PORT }}" \
           -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
           -e EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
           -e EMAIL_FROM="${{ secrets.EMAIL_FROM }}" \
           -e EMAIL_ADMIN="${{ secrets.EMAIL_ADMIN }}" \
           -e RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
        doitformellc/harborgroupusa:latest
      
